In [1]:
import numpy as np

In [33]:
arr = np.arange(0,11)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# Slicing an array from start to end 
arr[1:5]

array([1, 2, 3, 4])

In [8]:
# By not putting a start index it defaults to 0
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
# This will broadcast the = number to the first 5 numbers (0:5)
arr[0:5] = 100

In [32]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
slice_of_arr = arr[0:6]

In [36]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [39]:
slice_of_arr[:] = 99

In [40]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [46]:
# Call copy if you do not want to change the orignal array
arr_copy = arr.copy()

In [42]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [43]:
arr_copy[:] = 100

In [44]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr_2d = np.array([[5,10,15],[20,25,20],[35,40,45]])

In [54]:
# This is the same as callling arr_2d[2][1]
arr_2d[2,1]

40

In [55]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 20]])

In [56]:
arr_2d[1:2]

array([[20, 25, 20]])

In [57]:
arr = np.arange(1,11)

In [60]:
# Returns an array and checks the conditional against every value int he array
bool_arr = arr > 5

In [61]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [62]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])