In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Used the same was as range, first param is start, second param is end. Third param is step size
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
# How many zeros you want to print
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# Evenly spaces out values from first param to second param. Third param determines how many
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# One dimension array to 1
np.random.rand(5)

array([0.01716652, 0.11542082, 0.48511549, 0.20017415, 0.10183185])

In [14]:
# One dimensional array will give you to random numbers
np.random.randn(2)

array([0.15509466, 0.32815632])

In [15]:
# Will give you a random int from first param to second, you can pass a third param for that many random numbers
np.random.randint(1,100,3)

array([77, 65, 66])

In [16]:
arr = np.arange(25)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
ranarr = np.random.randint(0,50,10)

In [19]:
ranarr

array([25, 15, 44, 12, 46, 44,  3, 36, 41, 38])

In [28]:
# Reshape lets you change the shape of the arr you have
# if the number of values do not match you will get an error
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
# Will get the max/min value of the array
ranarr.max()
ranarr.min()

3

In [24]:
# Will return the index value of the min/max value
ranarr.argmax()
ranarr.argmin()

6

In [31]:
# Will return the data type in your array
arr.dtype

dtype('int64')

In [32]:
from numpy.random import randint

In [33]:
randint(2,3)

2