In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# Used the same was as range, first param is start, second param is end. Third param is step size
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [21]:
# How many zeros you want to print
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
# Evenly spaces out values from first param to second param. Third param determines how many
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# One dimension array to 1
np.random.rand(5)

array([0.82750127, 0.1020161 , 0.28418142, 0.14517735, 0.11224027])

In [28]:
# One dimensional array will give you to random numbers
np.random.randn(2)

array([-1.27445407,  0.13217478])

In [31]:
# Will give you a random int from first param to second, you can pass a third param for that many random numbers
np.random.randint(1,100,3)

array([44, 43, 39])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([42, 17, 25,  8, 23, 46, 33, 37, 11, 38])

In [36]:
# Reshape lets you change the shape of the arr you have
# if the number of values do not match you will get an error
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])